### ISSUE TITLE
Dynamic Add and Remove Server

### ISSUE THREAD

**Issue by dylanhansch** [cmastudios/mcmdd#1]
Ability to send a command to the daemon via the panel (over unix socket) to add a server as well as remove a server and delete or keep it's files. What I mean by dynamic is that the daemon would not need to be restarted in order to apply the changes. (Create/Delete server)

Create Server: Should be able to specify game type. (IE: Garry's Mod, Team Fortress 2, CS:GO etc.)
Delete Server: Can just delete server from config or delete files as well as entry in the config.

**Comment by cmastudios** [comment]
How I plan to implement this:
- [ ] Make a subroutine to write config files. Probably make it find all sections and then search for all records in each section then write them.
- [ ] Instead of a hacky dynamic list that is a headache to manage in the main class, change it to use a stack initialized list of server structs with constant memory, with a max of 255 servers per daemon.
- [ ] Make a routine to create a server, that can `mkdir` the folder basically and add to the server list.
- [ ] Make a routine to delete a server, that can `mv` the folder somewhere else (/var/cache)
- [ ] Add to the protocol, calls to create server, delete server, set config variable, and write config. They can only be used when logged in as server . with a password in the auth field of the global config.

Templates for creating a server will be added as a part of #2.

The way the panel would use this would be to login as admin to the daemon section, set the proper config sections, run create server, then save config.

Warning: this would not be safe in an untrusted environment, such as with clients. One server has enough permission to `ls` and `rm` files in another directory, as everything is owned by one daemon user. The proper way to be secure is to isolate by user or by container.

I can work on this later, lots of work this week.

**Comment by cmastudios** [comment]
Implemented through docker and a bunch of CGI scripts.
